### ISSUE TITLE
ask 

### ISSUE THREAD

**Issue by hasanelfalakiy** [vyfor/kotlinite#1]
I want to know whether this kotlin language server will support/can be used for android editor applications? for example: SoraEditor? because the sora editor library supports language server ports

**Comment by vyfor** [comment]
Hey! It is intended to work with any editor that supports the LSP (Language Server Protocol). Though, the project is still in its early stages and very far from being complete.

**Comment by hasanelfalakiy** [comment]
> Hey! It is intended to work with any editor that supports the LSP (Language Server Protocol). Though, the project is still in its early stages and very far from being complete.

that sounds interesting, would you like to check out the sora editor lsp api so that from the start of your project you can use this in sora editor, here is the repository: https://github.com/Rosemoe/sora-editor.git

**Comment by hasanelfalakiy** [comment]
> Hey! It is intended to work with any editor that supports the LSP (Language Server Protocol). Though, the project is still in its early stages and very far from being complete.

because until now no one has been able to implement kotlin lsp in the android editor

**Comment by vyfor** [comment]
From the looks of it, it [does](https://github.com/Rosemoe/sora-editor/tree/main/editor-lsp) seem to support the protocol, and *should* work seamlessly with any language server, including this one. I'm not familiar with Sora, so it might be a good idea to confirm this with them instead.

**Comment by hasanelfalakiy** [comment]
> From the looks of it, it [does](https://github.com/Rosemoe/sora-editor/tree/main/editor-lsp) seem to support the protocol, and *should* work seamlessly with any language server, including this one. I'm not familiar with Sora, so it might be a good idea to confirm this with them instead.

yeah that's a good idea
